import type { ComponentType } from "react";
import { lazy } from "react";

// One line per component. Preview pages load demos from here.
export const demos: Record<string, ComponentType> = {
  "glass-button": lazy(() => import("./core/glass-button/demo")),
  "particle-hero": lazy(() => import("./core/particle-hero/demo")),
  "decrypt-text": lazy(() => import("./core/decrypt-text/demo")),
  "ascii-dither-media": lazy(() => import("./core/ascii-dither-media/demo")),
  "glass-panel": lazy(() => import("./core/glass-panel/demo")),
  "magnetic-dock": lazy(() => import("./core/magnetic-dock/demo")),
  "dynamic-weight-text": lazy(() => import("./core/dynamic-weight-text/demo")),
  "hold-to-confirm": lazy(() => import("./core/hold-to-confirm/demo")),
  "signal-terrain": lazy(() => import("./core/signal-terrain/demo")),
  "particle-tunnel-scrub": lazy(() => import("./core/particle-tunnel-scrub/demo")),
  "slide-to-shatter": lazy(() => import("./core/slide-to-shatter/demo")),
  "mercury-minimap": lazy(() => import("./core/mercury-minimap/demo")),
  "singularity-text": lazy(() => import("./loud/singularity-text/demo")),
  "prism-drag-split": lazy(() => import("./loud/prism-drag-split/demo")),
  "cardio-baseline": lazy(() => import("./core/cardio-baseline/demo")),
  "chronicle-bar": lazy(() => import("./core/chronicle-bar/demo")),
  "crack-compare": lazy(() => import("./core/crack-compare/demo")),
  "ligature-melt": lazy(() => import("./core/ligature-melt/demo")),
  "moire-dial": lazy(() => import("./core/moire-dial/demo")),
  "respire-field": lazy(() => import("./core/respire-field/demo")),
  "vapor-countdown": lazy(() => import("./core/vapor-countdown/demo")),
  "warp-lattice": lazy(() => import("./core/warp-lattice/demo")),
  "erosion-trail": lazy(() => import("./loud/erosion-trail/demo")),
  "frost-scrub": lazy(() => import("./loud/frost-scrub/demo")),
  "sediment-stack": lazy(() => import("./core/sediment-stack/demo")),
  "ripple-unfold": lazy(() => import("./core/ripple-unfold/demo")),
  "drape-menu": lazy(() => import("./core/drape-menu/demo")),
  "frostbite-switch": lazy(() => import("./core/frostbite-switch/demo")),
  "flock-stack": lazy(() => import("./core/flock-stack/demo")),
  "rule-sparkline": lazy(() => import("./core/rule-sparkline/demo")),
  "scroll-caliper": lazy(() => import("./core/scroll-caliper/demo")),
  "solargraph-hero": lazy(() => import("./core/solargraph-hero/demo")),
  "aurora-flow-chart": lazy(() => import("./loud/aurora-flow-chart/demo")),
  "event-horizon-command": lazy(() => import("./loud/event-horizon-command/demo")),
  "fling-segment": lazy(() => import("./core/fling-segment/demo")),
  "tide-gauge-password": lazy(() => import("./core/tide-gauge-password/demo")),
  "loupe-slider": lazy(() => import("./core/loupe-slider/demo")),
  "caustic-select": lazy(() => import("./core/caustic-select/demo")),
  "cipher-reel-otp": lazy(() => import("./core/cipher-reel-otp/demo")),
  "needle-stepper": lazy(() => import("./core/needle-stepper/demo")),
  "updraft-dropzone": lazy(() => import("./core/updraft-dropzone/demo")),
  "terminator-date-field": lazy(() => import("./core/terminator-date-field/demo")),
  "lodestone-hero": lazy(() => import("./core/lodestone-hero/demo")),
  "strandline": lazy(() => import("./core/strandline/demo")),
  "heatwave-ledger": lazy(() => import("./core/heatwave-ledger/demo")),
  "caustic-coverflow": lazy(() => import("./core/caustic-coverflow/demo")),
  "counterpoise-tiers": lazy(() => import("./core/counterpoise-tiers/demo")),
  "scan-sweep-stats": lazy(() => import("./core/scan-sweep-stats/demo")),
  "core-sample-scroll": lazy(() => import("./loud/core-sample-scroll/demo")),
  "knockout-404": lazy(() => import("./loud/knockout-404/demo")),
};
