export interface TestimonialSubmission {
  name: string;
  role: string;
  company: string;
  profileUrl: string;
  photoUrl?: string;
  quote: string;
}

export interface NormalizedSubmission {
  name: string;
  role: string;
  company: string;
  profileUrl: string;
  photoUrl?: string;
  quote: string;
}

export type SubmissionValidationResult =
  | { ok: true; value: NormalizedSubmission }
  | { ok: false; code: string };

const URL_PATTERN = /https?:\/\/[^\s<>"'`]+/gi;
const EMAIL_PATTERN = /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i;
const PHONE_PATTERN =
  /(?:\+?\d{1,3}[\s.-]?)?(?:\(?\d{3}\)?[\s.-]?)\d{3}[\s.-]?\d{4}\b/;

const CONTACT_PHRASES = [
  "email me",
  "reach out",
  "dm me",
  "text me",
  "call me",
  "contact me",
  "whatsapp me",
];

const BOT_MARKERS = [
  "as an ai",
  "generated by ai",
  "written by ai",
  "chatgpt",
  "copilot",
  "i am a bot",
  "bot",
  "automated",
  "machine generated",
];

const CRYPTO_MARKERS = [
  "crypto",
  "bitcoin",
  "blockchain",
  "web3",
  "nft",
  "token",
  "airdrop",
  "defi",
  "memecoin",
];

const SEO_MARKERS = [
  "seo",
  "search engine optimization",
  "backlinks",
  "organic traffic",
  "rank higher",
  "search rankings",
  "domain authority",
  "keywords",
  "link building",
  "serp",
];

const PROMOTIONAL_MARKERS = [
  "buy now",
  "sign up",
  "book a call",
  "free trial",
  "get started",
  "try now",
  "learn more",
  "visit our",
  "contact us",
  "schedule a demo",
  "start now",
];

const SCORE_WEIGHTS: Record<string, number> = {
  too_many_urls: 35,
  repeated_tokens: 20,
  contact_solicitation: 25,
  crypto_promotion: 30,
  seo_promotion: 30,
  promotional_cta: 15,
  bot_marker: 40,
};

function normalizeText(value: string): string {
  return value.trim().replace(/\s+/g, " ");
}

function combinedText(input: TestimonialSubmission | NormalizedSubmission): string {
  return [input.name, input.role, input.company, input.quote].join(" ");
}

function stripUrls(value: string): string {
  return value.replace(URL_PATTERN, " ");
}

function tokenize(value: string): string[] {
  return value
    .toLocaleLowerCase("en-US")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .match(/[a-z0-9]+/g)
    ?? [];
}

function countUrls(value: string): number {
  return value.match(URL_PATTERN)?.length ?? 0;
}

function hasRepeatedTokens(value: string): boolean {
  const counts = new Map<string, number>();
  for (const token of tokenize(stripUrls(value))) {
    if (token.length < 4) continue;
    counts.set(token, (counts.get(token) ?? 0) + 1);
    if ((counts.get(token) ?? 0) >= 3) return true;
  }
  return false;
}

function normalizeSearchTokens(value: string): string[] {
  return tokenize(value);
}

function includesPhrase(value: string, phrase: string): boolean {
  const haystack = normalizeSearchTokens(value);
  const needle = normalizeSearchTokens(phrase);

  if (needle.length === 0 || haystack.length < needle.length) return false;

  for (let index = 0; index <= haystack.length - needle.length; index += 1) {
    let matched = true;
    for (let offset = 0; offset < needle.length; offset += 1) {
      if (haystack[index + offset] !== needle[offset]) {
        matched = false;
        break;
      }
    }
    if (matched) return true;
  }

  return false;
}

function includesAny(value: string, phrases: readonly string[]): boolean {
  return phrases.some((phrase) => includesPhrase(value, phrase));
}

function hasContactSolicitation(value: string): boolean {
  return EMAIL_PATTERN.test(value) || PHONE_PATTERN.test(value) || includesAny(value, CONTACT_PHRASES);
}

function hasBotMarker(value: string): boolean {
  return includesAny(value, BOT_MARKERS);
}

function hasCryptoPromotion(value: string): boolean {
  return includesAny(value, CRYPTO_MARKERS);
}

function hasSeoPromotion(value: string): boolean {
  return includesAny(value, SEO_MARKERS);
}

function hasPromotionalCta(value: string): boolean {
  return includesAny(value, PROMOTIONAL_MARKERS);
}

function normalizeUrlField(value?: string): string {
  return normalizeText(value ?? "");
}

function validateUrl(value: string): { ok: true; value: string } | { ok: false; code: string } {
  if (value.length === 0) return { ok: false, code: "invalid_url" };
  if (value.length > 240) return { ok: false, code: "url_too_long" };

  let url: URL;
  try {
    url = new URL(value);
  } catch {
    return { ok: false, code: "invalid_url" };
  }

  if (url.protocol !== "http:" && url.protocol !== "https:") {
    return { ok: false, code: "unsupported_url_protocol" };
  }

  return { ok: true, value: url.toString() };
}

export function normalizeSubmission(input: TestimonialSubmission): NormalizedSubmission {
  const normalizedPhotoUrl = normalizeUrlField(input.photoUrl);
  const normalized: NormalizedSubmission = {
    name: normalizeText(input.name),
    role: normalizeText(input.role),
    company: normalizeText(input.company),
    profileUrl: normalizeUrlField(input.profileUrl),
    quote: normalizeText(input.quote),
  };

  if (normalizedPhotoUrl) {
    normalized.photoUrl = normalizedPhotoUrl;
  }

  return normalized;
}

export function scoreSubmission(input: TestimonialSubmission | NormalizedSubmission): {
  score: number;
  flags: string[];
} {
  const normalized = normalizeSubmission(input);
  const value = combinedText(normalized);
  const urlCount =
    countUrls(normalized.name) +
    countUrls(normalized.role) +
    countUrls(normalized.company) +
    countUrls(normalized.quote) +
    countUrls(normalized.profileUrl) +
    countUrls(normalized.photoUrl ?? "");
  const flags: string[] = [];

  if (urlCount > 2) flags.push("too_many_urls");
  if (hasRepeatedTokens(value)) flags.push("repeated_tokens");
  if (hasContactSolicitation(value)) flags.push("contact_solicitation");
  if (hasCryptoPromotion(value)) flags.push("crypto_promotion");
  if (hasSeoPromotion(value)) flags.push("seo_promotion");
  if (hasPromotionalCta(value)) flags.push("promotional_cta");
  if (hasBotMarker(value)) flags.push("bot_marker");

  const score = Math.max(
    0,
    Math.min(100, flags.reduce((total, flag) => total + (SCORE_WEIGHTS[flag] ?? 0), 0)),
  );

  return { score, flags };
}

export const MAX_QUOTE_LENGTH = 800;
export const MAX_NAME_LENGTH = 80;

export function validateSubmission(
  input: TestimonialSubmission,
): { ok: true; value: NormalizedSubmission } | { ok: false; code: string } {
  const normalized = normalizeSubmission(input);

  if (!normalized.name) return { ok: false, code: "empty_name" };
  if (!normalized.role) return { ok: false, code: "empty_role" };
  if (!normalized.quote) return { ok: false, code: "empty_quote" };
  if (normalized.name.length > MAX_NAME_LENGTH) return { ok: false, code: "name_too_long" };
  if (normalized.quote.length > MAX_QUOTE_LENGTH) return { ok: false, code: "quote_too_long" };

  const profileUrl = validateUrl(normalized.profileUrl);
  if (!profileUrl.ok) return profileUrl;

  let photoUrl: string | undefined;
  if (normalized.photoUrl) {
    const photoUrlResult = validateUrl(normalized.photoUrl);
    if (!photoUrlResult.ok) return photoUrlResult;
    photoUrl = photoUrlResult.value;
  }

  return {
    ok: true,
    value: {
      ...normalized,
      profileUrl: profileUrl.value,
      ...(photoUrl ? { photoUrl } : {}),
    },
  };
}
