// Generates registry/index.tsx — the lazy demo map the preview pages load from.
//
// This used to be hand-maintained, one line per component, which made it the single
// worst file in the repo for parallel work: every branch that adds a component edits
// the same block, so every merge conflicts, and an early breeding round hit a real
// concurrent-write race here. Deriving it from the folder structure means the file is
// never hand-edited and a conflict is resolved by regenerating, not by hand-merging.
import { readdirSync, existsSync, writeFileSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const entries: { name: string; collection: string }[] = [];
for (const collection of ["core", "loud"]) {
  const dir = join(ROOT, "registry", collection);
  if (!existsSync(dir)) continue;
  for (const name of readdirSync(dir).sort()) {
    // a component is only registrable if it actually has a demo to load
    if (!existsSync(join(dir, name, "demo.tsx"))) continue;
    entries.push({ name, collection });
  }
}

const lines = entries
  .map(
    (e) =>
      `  ${JSON.stringify(e.name)}: lazy(() => import("./${e.collection}/${e.name}/demo")),`
  )
  .join("\n");

const out = `// GENERATED by scripts/build-index.ts — do not edit by hand.
// Add a component by creating registry/<collection>/<name>/demo.tsx, then run
// \`npm run registry:build\`. On a merge conflict here, regenerate rather than merge.
import type { ComponentType } from "react";
import { lazy } from "react";

export const demos: Record<string, ComponentType> = {
${lines}
};
`;

const target = join(ROOT, "registry", "index.tsx");
const prev = existsSync(target) ? readFileSync(target, "utf8") : "";
if (prev !== out) writeFileSync(target, out);
console.log(`registry/index.tsx: ${entries.length} demo(s)`);
