// Single-source registry build: meta.json sidecars are the only authority.
// Generates registry.json from them, then runs `shadcn build` → public/r/.
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { REGISTRY_ORIGIN } from "../lib/registry-origin.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const items = [];
const mismatched: { folder: string; metaName: string }[] = [];
for (const collection of ["core", "loud"]) {
  const dir = join(ROOT, "registry", collection);
  if (!existsSync(dir)) continue;
  for (const name of readdirSync(dir).sort()) {
    const metaPath = join(dir, name, "meta.json");
    if (!existsSync(metaPath)) continue;
    // Hard failure, but name the file: a bare JSON.parse here reports only
    // "Unexpected token" across 285+ sidecars, so one trailing comma takes
    // down the build with no way to tell which folder did it.
    let meta;
    try {
      meta = JSON.parse(readFileSync(metaPath, "utf8"));
    } catch (e) {
      throw new Error(
        `${metaPath}: ${e instanceof Error ? e.message : String(e)}`
      );
    }
    if (meta.name !== name) mismatched.push({ folder: name, metaName: meta.name });
    items.push({
      name: meta.name,
      type: "registry:ui",
      title: meta.title,
      description: meta.description,
      files: [
        {
          path: `registry/${collection}/${name}/component.tsx`,
          type: "registry:ui",
          target: `components/ui/${name}.tsx`,
        },
      ],
      dependencies: meta.dependencies,
      meta: {
        collection: meta.collection,
        tags: meta.tags,
        instruction: meta.instruction,
      },
    });
  }
}

// Loud guard: build-registry keys items by meta.name while build-index keys
// demos by folder name, so a mismatch ships an installable /r/<name>.json
// whose preview has no demo — installable but unpreviewable.
//
// Warning rather than a build failure on purpose, following the order guard
// below: the in-flight registry batch must not be blocked by a hard gate.
// ponytail: ceiling — a warning can be scrolled past in CI, so a mismatch can
// still ship. Upgrade path: flip to `throw` once the batch lands and the tree
// is known-clean.
if (mismatched.length > 0) {
  console.warn(
    `\n  WARNING: ${mismatched.length} meta.json name(s) do not match their folder.\n` +
      `  The demo is keyed by folder, so /r/<name>.json installs with no preview.\n` +
      `  Fix: set "name" in meta.json to the folder name (or rename the folder)\n` +
      `  Mismatched: ${mismatched
        .slice(0, 12)
        .map((m) => `${m.folder} (name: ${m.metaName})`)
        .join(", ")}${mismatched.length > 12 ? `, +${mismatched.length - 12} more` : ""}\n`
  );
}

writeFileSync(
  join(ROOT, "registry.json"),
  JSON.stringify(
    {
      $schema: "https://ui.shadcn.com/schema/registry.json",
      name: "ns-ui",
      // Single source of truth (lib/registry-origin.ts) — same origin the
      // showcase and llms.txt install commands use, so this can't drift.
      homepage: REGISTRY_ORIGIN,
      items,
    },
    null,
    2
  ) + "\n"
);
console.log(`registry.json: ${items.length} item(s) from meta sidecars`);

// Loud guard: every component must have a recency rank in
// lib/component-order.json, or it sorts LAST in the catalog's "Newest" view
// instead of first — so a freshly built component is the hardest one to find,
// which is the exact opposite of what you want after building it.
//
// This is a warning rather than a build failure on purpose: that file is
// DELIBERATELY not chained into this script (see scripts/build-order.ts —
// git history is unreliable on a Vercel shallow clone, so the snapshot is
// committed and regenerated by hand). A hard failure here would break every
// deploy that legitimately ships an unranked component. But it went unnoticed
// twice — 16 components once, then 22 more — so silence was clearly the wrong
// default.
try {
  const order: string[] = JSON.parse(
    readFileSync(join(ROOT, "lib/component-order.json"), "utf8")
  );
  const ranked = new Set(order);
  const unranked = items.map((i) => i.name).filter((n) => !ranked.has(n));
  if (unranked.length > 0) {
    console.warn(
      `\n  WARNING: ${unranked.length} component(s) missing from lib/component-order.json.\n` +
        `  They will sort LAST under "Newest" in the catalog, not first.\n` +
        `  Fix: npm run order:build   (then commit lib/component-order.json)\n` +
        `  Unranked: ${unranked.slice(0, 12).join(", ")}${unranked.length > 12 ? `, +${unranked.length - 12} more` : ""}\n`
    );
  }
} catch {
  // No order file yet (fresh clone before the first order:build) — not worth
  // failing a build over.
}
execFileSync("npx", ["shadcn", "build"], { cwd: ROOT, stdio: "inherit" });
