// Generates mcp/data/registry-snapshot.json — the offline copy of the
// registry the MCP server ships inside its npm package (mcp/). The server
// cannot read registry.json, public/llms-full.txt or registry/{core,loud}/
// off disk once installed from npm: the repo isn't there. So this script,
// which runs where the repo IS present, bakes everything the server needs
// (search fields, prop signatures, categories, source, install command)
// into one JSON file at publish time.
//
// Chained into `npm run registry:build`, after build-llms.ts (its input,
// public/llms-full.txt, must already exist) and after build-registry.ts
// (registry.json). Not committed — see .gitignore — regenerated by
// `prepack` in mcp/package.json before every `npm publish`, same pattern
// as every other generated file in this repo.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { REGISTRY_ORIGIN } from "../lib/registry-origin.ts";
import { CATEGORIES, categorize } from "../lib/search-categories.ts";
import { kindOf } from "../lib/kind.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "mcp", "data");
const OUT_FILE = join(OUT_DIR, "registry-snapshot.json");

type RegistryItem = {
  name: string;
  title: string;
  description: string;
  dependencies: string[];
  meta: { collection: string; tags: string[]; instruction: string };
};

const registryPath = join(ROOT, "registry.json");
const llmsFullPath = join(ROOT, "public", "llms-full.txt");
if (!existsSync(registryPath)) {
  throw new Error(
    "registry.json not found — run this after build-registry.ts, not standalone."
  );
}
if (!existsSync(llmsFullPath)) {
  throw new Error(
    "public/llms-full.txt not found — run this after build-llms.ts, not standalone."
  );
}

const registry: { name: string; items: RegistryItem[] } = JSON.parse(
  readFileSync(registryPath, "utf8")
);

// --- parse public/llms-full.txt into per-component blocks -----------------
// Blocks are separated by a blank line before each "## <name>  [collection]"
// header (see build-llms.ts's renderBlock/HEADER). Reusing the rendered text
// instead of re-implementing the prop-signature scanner keeps this script
// from drifting out of sync with that logic.
const llmsFull = readFileSync(llmsFullPath, "utf8");
// Split on the blank-line-then-header boundary rather than matching each
// block with a lookahead: `$` in multiline mode matches before every `\n`,
// not just the final one, so a non-greedy lookahead for "end of block" was
// stopping at the first line instead of the next "## " header.
const headerRe = /^## (\S+)\s+\[(\w+)]$/m;
const rawBlocks = llmsFull.split(/\n(?=## )/).filter((b) => headerRe.test(b));
type Block = { useWhen: string; props: string; installCommand: string };
const blocksByName = new Map<string, Block>();
for (const raw of rawBlocks) {
  const headerMatch = raw.match(headerRe)!;
  const name = headerMatch[1];
  const body = raw.slice(headerMatch[0].length);
  const useWhenMatch = body.match(/^use when: ([\s\S]*?)\n(?=props:)/m);
  const propsMatch = body.match(/^props:\n?([\s\S]*?)\n(?=deps:)/m);
  const installMatch = body.match(/^install: (.+)$/m);
  if (!useWhenMatch || !propsMatch || !installMatch) {
    throw new Error(
      `mcp snapshot: could not parse llms-full.txt block for "${name}" — ` +
        `regenerate public/llms-full.txt (npm run llms:build) and check its format hasn't changed.`
    );
  }
  const propsRaw = propsMatch[1];
  // Single-line props (e.g. "(none)") appear inline after "props: " rather
  // than on indented following lines — recover that case too.
  const props =
    propsRaw.trim().length > 0
      ? propsRaw
          .split("\n")
          .map((l) => l.replace(/^ {2}/, ""))
          .join("\n")
          .trim()
      : (body.match(/^props: (.+)$/m)?.[1].trim() ?? "");
  blocksByName.set(name, {
    useWhen: useWhenMatch[1].trim(),
    props,
    installCommand: installMatch[1].trim(),
  });
}

// --- categories -------------------------------------------------------------
const categoryIdsByName = categorize(
  registry.items.map((it) => ({ name: it.name, tags: it.meta.tags }))
);

// --- assemble one entry per component ---------------------------------------
const missingBlock: string[] = [];
const missingSource: string[] = [];

const components = registry.items.map((item) => {
  const block = blocksByName.get(item.name);
  if (!block) missingBlock.push(item.name);

  const sourcePath = join(
    ROOT,
    "registry",
    item.meta.collection,
    item.name,
    "component.tsx"
  );
  let source = "";
  if (existsSync(sourcePath)) {
    source = readFileSync(sourcePath, "utf8");
  } else {
    missingSource.push(item.name);
  }

  return {
    name: item.name,
    title: item.title,
    description: item.description,
    collection: item.meta.collection,
    tags: item.meta.tags,
    kind: kindOf(item.meta.tags),
    categories: categoryIdsByName.get(item.name) ?? [],
    useWhen: block?.useWhen ?? "",
    props: block?.props ?? "(unresolved — read the source)",
    instruction: item.meta.instruction,
    dependencies: item.dependencies,
    installCommand:
      block?.installCommand ??
      `npx shadcn add ${REGISTRY_ORIGIN}/r/${item.name}.json`,
    sourcePath: `registry/${item.meta.collection}/${item.name}/component.tsx`,
    source,
  };
});

// Fail loud rather than ship a snapshot with silently-empty fields (see
// AGENTS.md's own rule for the scanner this depends on: warn/fail, don't guess).
if (missingBlock.length) {
  throw new Error(
    `mcp snapshot: ${missingBlock.length} component(s) had no llms-full.txt block: ${missingBlock.join(", ")}`
  );
}
if (missingSource.length) {
  throw new Error(
    `mcp snapshot: ${missingSource.length} component(s) had no component.tsx on disk: ${missingSource.join(", ")}`
  );
}

const categories = CATEGORIES.map((c) => ({
  id: c.id,
  label: c.label,
  count: components.filter((comp) => comp.categories.includes(c.id)).length,
}));

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(
  OUT_FILE,
  JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      registryOrigin: REGISTRY_ORIGIN,
      registryName: registry.name,
      collections: ["core", "loud"],
      categories,
      components,
    },
    null,
    2
  ) + "\n"
);

console.log(
  `mcp snapshot: ${components.length} component(s), ${categories.length} categories -> mcp/data/registry-snapshot.json`
);
