import assert from "node:assert/strict";
import { ALEX_TESTIMONIAL, ALEX_TESTIMONIAL_SEED } from "../lib/testimonials.ts";
import {
  normalizeSubmission,
  scoreSubmission,
  validateSubmission,
} from "../lib/testimonial-moderation.ts";

const cleanSubmission = { ...ALEX_TESTIMONIAL_SEED };
const cleanDisplayFixture = { ...ALEX_TESTIMONIAL };

assert.deepEqual(scoreSubmission(cleanDisplayFixture), { score: 0, flags: [] });
assert.deepEqual(scoreSubmission(cleanSubmission), { score: 0, flags: [] });
assert.deepEqual(validateSubmission(cleanSubmission), {
  ok: true,
  value: cleanSubmission,
});

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    photoUrl: "   ",
  }),
  {
    ok: true,
    value: cleanSubmission,
  },
);

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    photoUrl: "https://cdn.example.com/alex.jpg",
  }),
  {
    ok: true,
    value: {
      ...cleanSubmission,
      photoUrl: "https://cdn.example.com/alex.jpg",
    },
  },
);

assert.deepEqual(
  scoreSubmission({
    ...cleanSubmission,
    quote: "https://a.test https://b.test https://c.test",
  }),
  { score: 35, flags: ["too_many_urls"] },
);

assert.deepEqual(
  scoreSubmission({
    ...cleanSubmission,
    quote: "The bottom sheet made robotics tokenization examples easier to review.",
  }),
  { score: 0, flags: [] },
);

assert.deepEqual(
  scoreSubmission({
    ...cleanSubmission,
    quote: "design design design systems",
  }),
  { score: 20, flags: ["repeated_tokens"] },
);

assert.deepEqual(
  scoreSubmission({
    ...cleanSubmission,
    quote: "Email me at alex@example.com or call +1 (555) 123-4567.",
  }),
  { score: 25, flags: ["contact_solicitation"] },
);

assert.deepEqual(
  scoreSubmission({
    ...cleanSubmission,
    quote: "This crypto launch will help your web3 token community grow fast.",
  }),
  { score: 30, flags: ["crypto_promotion"] },
);

assert.deepEqual(
  scoreSubmission({
    ...cleanSubmission,
    quote: "Our SEO backlinks program will rank higher and drive organic traffic.",
  }),
  { score: 30, flags: ["seo_promotion"] },
);

assert.deepEqual(
  scoreSubmission({
    ...cleanSubmission,
    quote: "Book a call and sign up for a free trial today.",
  }),
  { score: 15, flags: ["promotional_cta"] },
);

assert.deepEqual(
  scoreSubmission({
    ...cleanSubmission,
    quote: "This testimonial was generated by ChatGPT and is fully automated.",
  }),
  { score: 40, flags: ["bot_marker"] },
);

assert.deepEqual(
  scoreSubmission({
    ...cleanSubmission,
    quote:
      "Crypto crypto crypto. Email me at alex@example.com, book a call, generated by ChatGPT, and improve SEO with backlinks.",
  }),
  {
    score: 100,
    flags: [
      "repeated_tokens",
      "contact_solicitation",
      "crypto_promotion",
      "seo_promotion",
      "promotional_cta",
      "bot_marker",
    ],
  },
);

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    name: "   Alex   Lekkas   ",
    role: "  Founding   Engineer  ",
    company: " Spawn   Partners ",
    profileUrl: "  https://www.linkedin.com/in/alexandros-lekkas/  ",
    photoUrl: "  https://cdn.example.com/alex.jpg  ",
    quote: "  Great   product   with   clean   docs.  ",
  }),
  {
    ok: true,
    value: {
      name: "Alex Lekkas",
      role: "Founding Engineer",
      company: "Spawn Partners",
      profileUrl: "https://www.linkedin.com/in/alexandros-lekkas/",
      photoUrl: "https://cdn.example.com/alex.jpg",
      quote: "Great product with clean docs.",
    },
  },
);

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    profileUrl: "ftp://example.com/alex",
  }),
  { ok: false, code: "unsupported_url_protocol" },
);

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    photoUrl: "ftp://example.com/alex.jpg",
  }),
  { ok: false, code: "unsupported_url_protocol" },
);

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    name: "",
  }),
  { ok: false, code: "empty_name" },
);

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    role: "",
  }),
  { ok: false, code: "empty_role" },
);

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    company: "",
  }),
  { ok: false, code: "empty_company" },
);

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    quote: "",
  }),
  { ok: false, code: "empty_quote" },
);

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    name: "A".repeat(81),
  }),
  { ok: false, code: "name_too_long" },
);

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    role: "A".repeat(81),
  }),
  { ok: false, code: "role_too_long" },
);

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    company: "A".repeat(81),
  }),
  { ok: false, code: "company_too_long" },
);

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    quote: "A".repeat(801),
  }),
  { ok: false, code: "quote_too_long" },
);

assert.deepEqual(
  validateSubmission({
    ...cleanSubmission,
    profileUrl: "https://example.com/" + "a".repeat(241),
  }),
  { ok: false, code: "url_too_long" },
);

assert.deepEqual(
  normalizeSubmission({
    ...cleanSubmission,
    name: "  Alex   Lekkas  ",
    role: "   Founding   Engineer ",
    company: " Spawn   Partners ",
    profileUrl: "  https://www.linkedin.com/in/alexandros-lekkas/ ",
    photoUrl: "  https://cdn.example.com/alex.jpg ",
    quote: "  Trim   and   collapse   whitespace.  ",
  }),
  {
    name: "Alex Lekkas",
    role: "Founding Engineer",
    company: "Spawn Partners",
    profileUrl: "https://www.linkedin.com/in/alexandros-lekkas/",
    photoUrl: "https://cdn.example.com/alex.jpg",
    quote: "Trim and collapse whitespace.",
  },
);

// --- hate / harassment screen -------------------------------------------
// Flagged at 100 so a match always quarantines. These assert the flag fires,
// not that the score is exactly 100 in combination with other flags.
for (const quote of [
  "kill all the developers who ship on friday",
  "those immigrants should leave",
]) {
  const { flags, score } = scoreSubmission({ ...cleanSubmission, quote });
  assert.ok(
    flags.includes("hate_or_harassment"),
    `expected hate_or_harassment for: ${quote}`,
  );
  assert.equal(score, 100, "hate flag must saturate the score");
}

// False-positive guards. An over-eager pattern silently quarantining real
// testimonials is the failure mode that actually costs something here, so
// ordinary copy containing these words must stay clean.
for (const quote of [
  "Women engineers on my team use this registry daily.",
  "This killed our design debt and the men and women here love it.",
  "We deport nothing; the components just work.",
  "I am trans and this design system is a joy to use.",
]) {
  const { flags } = scoreSubmission({ ...cleanSubmission, quote });
  assert.ok(
    !flags.includes("hate_or_harassment"),
    `false positive on legitimate copy: ${quote}`,
  );
}

console.log("testimonial moderation: pass");
